#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

test -f $sysresources    && xrdb -merge  $sysresources
test -f $sysmodmap       && xmodmap      $sysmodmap
test -f "$userresources" && xrdb -merge "$userresources"
test -f "$usermodmap"    && xmodmap     "$usermodmap"

# start some nice programs
eval $(ssh-agent)

test $(which dwmblocks) && dwmblocks &a
test $(which feh) && feh --bg-fill ~/Downloads/ganapathy-kumar-Gl9r22w_Oxk-unsplash.jpg &
test $(which picom) && picom --experimental-backends --blur-method dual_kawase --blur-strength 20 --config ~/.config/picom/picom.conf &
test $(which setxkbmap) && setxkbmap cz &
test $(which wmname) && wmname compiz &
test $(which gxkb) && gxkb &
test $(which nm-applet) && nm-applet &

if [ $(which xbanish) ]; then
    xbanish >>$HOME/.xbanish.log &    # https://github.com/jcs/xbanish
elif [ $(which unclutter) ]; then
    unclutter &
fi

# source machine- and uname-specific xinitrcs
xinitcfg="$HOME/.config/xinit"
test -f "$xinitcfg/u/$(uname)"       && . "$xinitcfg/u/$(uname)"
test -f "$xinitcfg/host/$(hostname)" && . "$xinitcfg/host/$(hostname)"

while true; do
	    # Log stderror to a file 
	dwm 2> ~/.dwm.log
		    # No error logging
		        #dwm >/dev/null 2>&1
done

# exit X when dwmstatus (or failsafe xterm) is killed
if [ $(which slstatus) ]; then
    slstatus
elif [ $(which dwmstatus) ]; then
    dwmstatus
elif [ $(which st) ]; then
    st
elif [ $(which urxvt) ]; then
    urxvt
elif [ $(which uxterm) ]; then
    uxterm -ls -T Failsafe -geometry 80x24-0-0
elif [ $(which rxvt) ]; then
    rxvt
elif [ $(which xterm) ]; then
    xterm -ls -T Failsafe -geometry 80x24-0-0
elif [ $(which gnome-terminal) ]; then
    gnome-terminal
fi
